name: Coveralls
on:
    pull_request:
        branches:
            - master
            - develop
    push:
        branches:
            - master
            - develop
jobs:
    install-and-coveralls:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: install
              run: yarn --network-timeout 600000

            - name: yarn add coveralls
              run: |
                  yarn add -D coveralls
                  yarn run test --coverage && cat ./coverage/lcov.info

            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
