name: Coveralls
on:
    pull_request:
        branches:
            - master
            - develop
    push:
        branches:
            - master
            - develop
jobs:
    install-and-coveralls:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: yarn install
              run: yarn --network-timeout 600000

            - name: yarn install coveralls
              run: |
                  yarn install -D coveralls
                  yarn run test --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.ACCESS_TOKEN }}
