name: Coveralls
on:
    push:
        branches:
            - master
            - develop
jobs:
    install-and-coveralls:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [8.x, 10.x, 12.x]

        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@master
              with:
                  node-version: ${{ matrix.node-version }}

            - name: yarn install
              run: yarn install

            - name: Coveralls
              run: yarn run test --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
