name: Coveralls
on:
    - pull_request
    - push:
          branches:
              - master
              - develop
jobs:
    install-and-coveralls:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: yarn install, make test-coverage
              run: |
                  yarn install
                  make test-coverage

            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.ACCESS_TOKEN }}
