name: Build and Deploy
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Build
              run: |
                  npm install
            #       npm run-script build
            #   env:
            #       GAID: ${{ secrets.GAID }}
            #       GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
            #       GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}

            - name: Deploy
              run: |
                  npm run-script deploy
              env:
                  GAID: ${{ secrets.GAID }}
                  GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
                  GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # - name: Deploy
            #   uses: JamesIves/github-pages-deploy-action@releases/v3
            #   with:
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #       BRANCH: gh-pages
            #       FOLDER: docs/.vuepress/dist
