name: Build and Deploy
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Build
              run: |
                  npm install
                  npm run-script build
              env:
                  GAID: ${{ secrets.GAID }}
                  GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
                  GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}

            - name: Deploy
              run: npm run-script deploy
              env:
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
